numberOfReviewers: 2

# This group should NEVER be changed based on availability; it's to help
# determine if a PR author is an external contributor.
team:
  - brettcannon
  - ericsnowcurrently
  - int19h
  - karthiknadig
  - karrtikr
  - kimadeline
  - luabud

# Comment yourself out when you will be unavailable for reviews for more than a
# couple of days.
reviewers:
  - ericsnowcurrently
  #- int19h
  - karthiknadig
  - karrtikr
  - kimadeline
