codecov:
  strict_yaml_branch: 'main'
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: '70...100'

  status:
    project:
      default:
        informational: true
        only_pulls: true
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  branches: ['main']
  layout: 'diff, files'
  behavior: default
  require_changes: no
