version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
    default_labels:
      - 'skip news'

  # Not skipping the news for Python dependencies in case it's actually useful to communicate to users.
  - package-ecosystem: 'pip'
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: 'pip'
    directory: /news
    schedule:
      interval: monthly
    default_labels:
      - 'skip news'
  # Activate when we feel ready to keep up with frequency.
  # - package-ecosystem: 'npm'
  #   directory: /
  #   schedule:
  #     interval: daily
  #   default_labels:
  #     - "skip news"
