language: python
cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
before_install: |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi
  git submodule update --init --recursive
  git clone https://github.com/creationix/nvm.git ./.nvm
  source ./.nvm/nvm.sh
  nvm install 8.9.1
  nvm use 8.9.1
  yarn global add vsce
  yarn global add azure-cli
  export TRAVIS_PYTHON_PATH=`which python`
install:
  - pip install --upgrade -r requirements.txt
  - yarn

script:
  - yarn run clean
  - yarn run vscode:prepublish
  - yarn run cover:enable
  - yarn run testSingleWorkspace --silent
  - if [ $TRAVIS_UPLOAD_COVERAGE == "true" ]; then
        bash <(curl -s https://codecov.io/bash);
    fi
  - yarn run clean
  - yarn run vscode:prepublish
  - yarn run cover:enable
  - yarn run testMultiWorkspace --silent
  - if [ $TRAVIS_UPLOAD_COVERAGE == "true" ]; then
        bash <(curl -s https://codecov.io/bash);
    fi
after_success:
  - if [ $AZURE_STORAGE_ACCOUNT ]; then
        yarn run clean;
        vsce package;
        azure storage blob upload --container $AZURE_STORAGE_CONTAINER --blob ms-python-insiders.vsix --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_ACCESS_KEY --file python*.vsix --quiet;
    fi
