language: python

python:
  - 2.7

sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - pip install .
  - pip install -r requirements.txt
  - npm install
  - npm run vscode:prepublish
  
script:
  - npm test --silent