language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
        - os: linux
          sudo: required
          python: 3.5

# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - pip install -r requirements.txt
  - npm install
  - npm run vscode:prepublish
  
script:
  - npm test --silent