name: General bug report
description: 'Issue with the Python extension, not supporting/sibling extensions (you may also use the `Python: Report Issue` command)'
labels: ['classify', 'bug']
body:
  - type: input
    attributes:
      label: VS Code version
      description: 'Can be found via the `Help: About` command'
    validations:
      required: true
