name: Bug Report
description: "Issue with the Python extension, not supporting/sibling extensions (you may also use the `Python: Report Issue` command)"
labels: ["bug", "classify"]
body:
body:
  - type: input
    attributes:
      label: VS Code version
      description: "Can be found via the `Help: About` command"
    validations:
      required: true
  - type: input
    attributes:
      label: Extension version
      description: 'Available under the Extensions side bar'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS type
      options: ['Windows', 'macOS', 'Linux', 'Other']
    validations:
      required: true
  - type: input
    attributes:
      label: OS version
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Python distribution
      options: ['python.org', 'Anaconda', 'Operating system', 'Other']
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Language server
      description: "The value of the `python.languageServer` setting"
      options: ['Default', 'Pylance', 'Jedi', 'None']
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: 'What do you think should have happened?'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: 'Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue'
      placeholder: 'If you think a GIF of what is happening would be helpful, consider tools like https://www.cockos.com/licecap/, https://github.com/phw/peek or https://www.screentogif.com/'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: 'Output for `Python` in the Output panel'
      placeholder: '`View` → `Output`, change the drop-down the upper-right of the `Output` panel to `Python`'
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/microsoft/vscode-python/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true