blank_issues_enabled: false
contact_links:
  - name: Pylance
    url: https://github.com/microsoft/pylance-release/issues
    about: For issues relating to the Pylance language server extension
  - name: debugpy
    url: https://github.com/microsoft/debugpy/issues
    about: For issues relating to the debugpy debugger
  - name: Jupyter
    url: https://github.com/microsoft/vscode-jupyter/issues
    about: For issues relating to the Jupyter extension
  - name: Help/Support
    url: https://github.com/microsoft/vscode-python/discussions/categories/q-a
    about: Please ask support questions in our "Q&A" Discussions category
