name: 'Lint'
description: 'Lint TypeScript and Python code'

inputs:
  node_version:
    description: 'Version of Node to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Node cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-lint-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-lint-

    - name: Install Node dependencies
      run: npm ci --prefer-offline
      shell: bash

    - name: Run `gulp prePublishNonBundle`
      run: npx gulp prePublishNonBundle
      shell: bash

    - name: Check dependencies
      run: npm run checkDependencies
      shell: bash

    - name: Lint TypeScript code
      run: npm run lint
      shell: bash

    - name: Check TypeScript format
      run: npm run format-check
      shell: bash

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-

    - name: Check Python format
      run: |
        python -m pip install -U black
        python -m black . --check
      working-directory: pythonFiles
      shell: bash
