name: Automation

on:
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: microsoft/pvscbot@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
