name: Issue labels

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  # From https://github.com/marketplace/actions/github-script#apply-a-label-to-an-issue.
  add-classify-label:
    name: "Add 'classify'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const labels = result.data.map((label) => label.name)

            const skipLabels = ['classify', 'needs community feedback', 'needs decision', 'needs PR', 'needs proposal', 'needs spike']
            const shouldSkipClassify = labels.some((label) => skipLabels.includes(label))

            if (!shouldSkipClassify) {
              console.log('This issue is not labeled with "classify" or a "needs __" label, add the "classify" label.')

              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['classify']
              })
            } else {
              console.log('This issue already has a "classify" or a "needs __" label, do not add the "classify" label.')
            }
